version: '4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_KRaft_RAFT_ENABLED: true
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
  
  topic-creator:
    container_name: topic-creator
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: /bin/sh -c 'sleep 10 &&
      kafka-topics --create --topic example --partitions 3 --replication-factor 1 --bootstrap-server kafka:29092'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

### Instructions after: docker-compose up

## Validate topic was created correctly:
# open cmd
# run: docker exec -it kafka /bin/bash
# run: kafka-topics --list --bootstrap-server localhost:9092
# will print a list of existing topics, make sure yours is created

## Write message to topic:
# run: kafka-console-producer --topic example --bootstrap-server localhost:9092
# each message is 1 liner, when pressing enter it will send what you type
# to exit the editor: ctrl + C